// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDziDHx5x7maRaq-zs_WaRFeoYqqDF0r9k',
    appId: '1:323787817664:web:254aab8c2cd4d8b064e325',
    messagingSenderId: '323787817664',
    projectId: 'collegeapp-2cefd',
    authDomain: 'collegeapp-2cefd.firebaseapp.com',
    databaseURL: 'https://collegeapp-2cefd-default-rtdb.firebaseio.com',
    storageBucket: 'collegeapp-2cefd.appspot.com',
    measurementId: 'G-9NLJ49FQX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChkrHmr_CHiDfMo1_7ryyk9F5MMFSyrHc',
    appId: '1:323787817664:android:289b516b68f8e74564e325',
    messagingSenderId: '323787817664',
    projectId: 'collegeapp-2cefd',
    databaseURL: 'https://collegeapp-2cefd-default-rtdb.firebaseio.com',
    storageBucket: 'collegeapp-2cefd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQRHWhRnlZs2tKQx_jyiCjldQiWD1rmds',
    appId: '1:323787817664:ios:150e3dd72d2b074364e325',
    messagingSenderId: '323787817664',
    projectId: 'collegeapp-2cefd',
    databaseURL: 'https://collegeapp-2cefd-default-rtdb.firebaseio.com',
    storageBucket: 'collegeapp-2cefd.appspot.com',
    iosBundleId: 'com.example.collegeProject',
  );
}
